url: "https://ferdowsi-lab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "The Ferdowsi Research Laboratory" # the name of your site, e.g. ACME Corp.
description: "on rheology of Earth materials and physics of Earth’s near-surface processes"
