menu:
- {name: 'Home', url: '/..'}
- {name: 'Publications', url: '/publications'}
- {name: 'People', url: '/people'}
- {name: 'Resources', url: '/resources'}
- {name: 'Join', url: '/positions'}


people:
- {name: 'Behrooz Ferdowsi', title: 'Assistant Professor', department: 'Civil and Environmental Engineering', institution: 'University of Houston', institution_address: 'Cullen College of Engineering, 4226 Martin Luther King Boulevard, TX 77204-4003', phone: '713-743-4293', email: 'bferdowsi@uh.edu', office: 'N115 Engineering Building 1', image: 'assets/img/BehroozFerdowsi.jpg', url: 'principal-investigator'}
- {name: 'Bimal Chhushyabaga', title: 'Graduate Research Assistant', department: 'Civil and Environmental Engineering', institution: 'University of Houston', institution_address: ' ', phone: ' ', email: 'bchhushy@cougarnet.uh.edu', office: ' ', image: 'assets/img/img_place_holder.jpg', url: 'graduate-students-bimal'}  
- {name: 'Aizhan Zhakupova', title: 'Graduate Research Assistant', department: 'Civil and Environmental Engineering', institution: 'University of Houston', institution_address: ' ', phone: ' ', email: 'azhakupo@cougarnet.uh.edu', office: ' ', image: 'assets/img/img_place_holder.jpg', url: 'graduate-students-aizhan'}


courses:
- {name: ' ', url: ' '}
- {name: ' ', url: ' '}
- {name: ' ', url: ' '}

contacts:
- {name: 'Dr. Behrooz Ferdowsi', title: 'Assistant Professor', department: 'Civil and Environmental Engineering', institution: 'University of Houston', institution_address: 'Cullen College of Engineering, 4726 Calhoun Road
Houston, TX 77204-4003', phone: '713-743-4293', email: 'bferdowsi@uh.edu', office: 'N115 Engineering Building 1', image: 'assets/img/contact.jpg'}
