menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Principal Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/principal-investigator.jpg', url: 'principal-investigator'}
- {name: 'Postdoctoral Researcher', title: 'Researcher', department: ' ', institution: ' ', institution_address: ' ', phone: ' ', email: ' ', office: ' ', image: ' ', url: 'postdoctoral-researchers'}
- {name: 'Graduate Student', title: 'Researcher', department: ' ', institution: ' ', institution_address: ' ', phone: ' ', email: ' ', office: ' ', image: ' ', url: 'graduate-students'}

courses:
- {name: ' ', url: ' '}
- {name: ' ', url: ' '}
- {name: ' ', url: ' '}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
